export const solutionsSpanish = [
  {
    id: 25,
    name: "Impulso Digital",
    price: 295,
    features: [
      "Catálogo básico digital",
      "Hasta 5 productos",
      "Organización simple de información",
      "Diseño funcional",
    ],
  },
  {
    id: 26,
    name: "Arranque Comercial",
    price: 630,
    features: [
      "Catálogo básico digital",
      "Hasta 10 productos",
      "Organización por categorías",
      "Botón de contacto directo",
    ],
  },
  {
    id: 27,
    name: "Catálogo Activo",
    price: 1620,
    features: [
      "Catálogo digital",
      "Hasta 20 productos",
      "Optimización para celular",
      "Integración con WhatsApp",
      "Diseño enfocado en conversión",
    ],
  },
  {
    id: 28,
    name: "Reconfiguración Estratégica",
    price: 1990,
    features: [
      "Reestructuración de catálogo existente (hasta 20 productos)",
      "Mejora de textos",
      "Optimización visual básica",
      "Organización profesional",
    ],
  },
  {
    id: 29,
    name: "Catálogo Profesional",
    price: 3890,
    features: [
      "Hasta 30 productos",
      "Diseño personalizado",
      "Categorías estructuradas",
      "Botones de contacto estratégicos",
    ],
  },
  {
    id: 30,
    name: "Impacto Visual",
    price: 5480,
    features: [
      "Catálogo digital",
      "Hasta 40 productos",
      "Edición básica de imágenes",
      "Optimización visual para ventas",
      "Estética tipo showroom",
    ],
  },
  {
    id: 31,
    name: "Catálogo Interactivo",
    price: 7910,
    features: [
      "Hasta 50 productos",
      "Navegación dinámica",
      "Botones por producto (cotizar / pedir)",
      "Experiencia tipo tienda",
    ],
  },
  {
    id: 32,
    name: "Flujo de Pedidos",
    price: 10300,
    features: [
      "Hasta 50 productos",
      "Sistema de solicitud de pedidos",
      "Formularios integrados",
      "Flujo de ventas estructurado",
    ],
  },
  {
    id: 33,
    name: "Expansión Multicanal",
    price: 13390,
    features: [
      "Catálogo digital",
      "Hasta 60 productos",
      "Adaptación para WhatsApp",
      "Versión ligera para compartir",
      "Optimización para difusión",
    ],
  },
  {
    id: 34,
    name: "Solución Empresarial",
    price: 16890,
    features: [
      "Catálogo digital",
      "Hasta 80 productos",
      "Diseño premium",
      "Categorías avanzadas",
      "Experiencia profesional",
    ],
  },
  {
    id: 35,
    name: "Catálogo con Producción Visual",
    price: 19730,
    features: [
      "Hasta 20 productos",
      "Sesión de fotografía básica",
      "Edición incluida",
      "Integración directa",
    ],
  },
  {
    id: 36,
    name: "Automatización Comercial",
    price: 23970,
    features: [
      "Hasta 50 productos",
      "Formularios inteligentes",
      "Organización automática de pedidos",
      "Optimización de procesos",
    ],
  },
  {
    id: 37,
    name: "Escala Mayorista",
    price: 25590,
    features: [
      "Catálogo digital",
      "Hasta 100 productos",
      "Estructura avanzada",
      "Preparado para alto volumen",
      "Organización robusta",
    ],
  },
  {
    id: 38,
    name: "Plataforma de Conversión Total",
    price: 32330,
    features: [
      "Hasta 100 productos",
      "Diseño + estrategia de ventas",
      "Optimización completa",
      "Experiencia enfocada en cierre",
      "Asesoría de uso",
    ],
  },
];


export const solutionsEnglish = [
  {
    id: 25,
    name: "Digital Boost",
    price: 295,
    features: [
      "Basic digital catalog",
      "Up to 5 products",
      "Simple information organization",
      "Functional design",
    ],
  },
  {
    id: 26,
    name: "Commercial Launch",
    price: 630,
    features: [
      "Basic digital catalog",
      "Up to 10 products",
      "Organization by categories",
      "Direct contact button",
    ],
  },
  {
    id: 27,
    name: "Active Catalog",
    price: 1620,
    features: [
      "Digital catalog",
      "Up to 20 products",
      "Mobile optimization",
      "WhatsApp integration",
      "Conversion-focused design",
    ],
  },
  {
    id: 28,
    name: "Strategic Reconfiguration",
    price: 1990,
    features: [
      "Restructuring of existing catalog (up to 20 products)",
      "Text improvement",
      "Basic visual optimization",
      "Professional organization",
    ],
  },
  {
    id: 29,
    name: "Professional Catalog",
    price: 3890,
    features: [
      "Up to 30 products",
      "Custom design",
      "Structured categories",
      "Strategic contact buttons",
    ],
  },
  {
    id: 30,
    name: "Visual Impact",
    price: 5480,
    features: [
      "Digital catalog",
      "Up to 40 products",
      "Basic image editing",
      "Visual optimization for sales",
      "Showroom-style aesthetic",
    ],
  },
  {
    id: 31,
    name: "Interactive Catalog",
    price: 7910,
    features: [
      "Up to 50 products",
      "Dynamic navigation",
      "Product buttons (quote / order)",
      "Store-like experience",
    ],
  },
  {
    id: 32,
    name: "Order Flow",
    price: 10300,
    features: [
      "Up to 50 products",
      "Order request system",
      "Integrated forms",
      "Structured sales flow",
    ],
  },
  {
    id: 33,
    name: "Multichannel Expansion",
    price: 13390,
    features: [
      "Digital catalog",
      "Up to 60 products",
      "Adaptation for WhatsApp",
      "Lightweight version for sharing",
      "Distribution optimization",
    ],
  },
  {
    id: 34,
    name: "Enterprise Solution",
    price: 16890,
    features: [
      "Digital catalog",
      "Up to 80 products",
      "Premium design",
      "Advanced categories",
      "Professional experience",
    ],
  },
  {
    id: 35,
    name: "Catalog with Visual Production",
    price: 19730,
    features: [
      "Up to 20 products",
      "Basic photo session",
      "Editing included",
      "Direct integration",
    ],
  },
  {
    id: 36,
    name: "Commercial Automation",
    price: 23970,
    features: [
      "Up to 50 products",
      "Smart forms",
      "Automatic order organization",
      "Process optimization",
    ],
  },
  {
    id: 37,
    name: "Wholesale Scale",
    price: 25590,
    features: [
      "Digital catalog",
      "Up to 100 products",
      "Advanced structure",
      "Prepared for high volume",
      "Robust organization",
    ],
  },
  {
    id: 38,
    name: "Total Conversion Platform",
    price: 32330,
    features: [
      "Up to 100 products",
      "Design + sales strategy",
      "Complete optimization",
      "Closing-focused experience",
      "Usage guidance",
    ],
  },
];
